homework-9
Bloodstinger/Mate pull request #3
Opened 2019-06-08 22:38 UTC by Bloodstinger

Implementation of linked list

2019-06-10 12:06 UTC, Sofasmile commented on src/lecture/eight/linked/list/CustomLinkedList.java
> +    transient private int listSize;
why do we use transient here?

2019-06-10 12:06 UTC, Sofasmile commented on src/lecture/eight/linked/list/CustomLinkedList.java
> +        T item;
add access modifier

2019-06-10 12:06 UTC, Sofasmile commented on src/lecture/eight/linked/list/CustomLinkedList.java
> +public class CustomLinkedList<T> implements List<T> {
please remember about logic organization of the class:  public methods, private methods

2019-06-10 12:06 UTC, Sofasmile commented on src/lecture/eight/linked/list/CustomLinkedList.java
> +    public void add(T value) {
better move logic from method linkLast() here

2019-06-10 12:06 UTC, Sofasmile commented on src/lecture/eight/linked/list/CustomLinkedList.java
> +    private void linkBefore(T item, Node<T> nodeAfter) {
try to use more understandable names

2019-06-10 12:06 UTC, Sofasmile commented on src/lecture/eight/linked/list/CustomLinkedList.java
> +        final Node<T> lastNode = last;
do we need final here?

2019-06-10 12:06 UTC, Sofasmile commented on src/lecture/eight/linked/list/CustomLinkedList.java
> +    private Node<T> node(int index) {
rename to getNode()

2019-06-10 12:06 UTC, Sofasmile commented on src/lecture/eight/linked/list/CustomLinkedList.java
> +        Object[] listArray = list.toArray();
try to use method add(T value) to simplify code

2019-06-10 12:06 UTC, Sofasmile commented on src/lecture/eight/linked/list/CustomLinkedList.java
> +                if (tNode.item == null) {
maybe better write:
if(Objects.IsNull(tNode.item == null) || t.equals(tNode.item))...

2019-06-10 12:06 UTC, Sofasmile commented on src/lecture/eight/linked/list/List.java
> +    T remove(int index); // возвращаем элемент, который удалили
remove comments please

2019-06-11 00:50 UTC, Bloodstinger commented
Added changes due to code review.

2019-06-11 11:37 UTC, SevostyanovGerman requested changes

2019-06-11 11:37 UTC, SevostyanovGerman commented on src/lecture/eight/linked/list/CustomLinkedList.java
> +        for (Object node :
is it ok convension?

2019-06-12 14:05 UTC, SevostyanovGerman requested changes

2019-06-12 14:05 UTC, SevostyanovGerman commented on src/lecture/eight/linked/list/CustomLinkedList.java
> +        return null;
return null bad practice

2019-06-14 14:27 UTC, SevostyanovGerman approved these changes

2019-06-14 14:27 UTC, SevostyanovGerman commented on src/lecture/eight/linked/list/CustomLinkedList.java
> +            for (Node<T> tNode = first; tNode != null; tNode = tNode.next) {
cs

2019-06-15 22:50 UTC, merged